[package]
name = "dike-lang-anchor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
dike-core = { path = "../dike-core" }
syn.workspace = true
proc-macro2.workspace = true
quote.workspace = true
blake3.workspace = true
